-- Create brands table
CREATE TABLE IF NOT EXISTS public.brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    "Name" text NOT NULL,
    logo text,
    return_policy text
);

-- Add foreign key to inventory_items table
ALTER TABLE public.inventory_items
    ADD COLUMN IF NOT EXISTS brand_id bigint REFERENCES public.brands(id);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_brands_name ON public.brands("Name");
CREATE INDEX IF NOT EXISTS idx_inventory_items_brand_id ON public.inventory_items(brand_id);

-- Insert initial brand data
INSERT INTO public.brands ("Name", logo, return_policy)
VALUES 
    ('Latin Quaters', 'data:image/png;base64,iVBORw0KGgoA', 'within 10 days of delivery'),
    ('Kazo', 'https://www.gpl.net.in/wp-content/uploa', NULL)
ON CONFLICT (id) DO NOTHING; 